export {default as Navbar} from "../components/navbar/Navbar"
export {default as Home} from "./home/Home"
export {default as Cabinet} from "../components/cabinet/Cabinet"
export {default as Register} from "../components/register/Register"
export {default as Cart} from "../components/cart/Cart"
export {default as Account } from "../components/account/Account"
export {default as InfoProduct} from "../components/info/InfoPorudct"
export {default as Barkery} from "../components/category/Barkery"
export {default as Dairy} from "../components/category/Dairy"
export {default as Snack} from "../components/category/Snack"
export {default as Drinks} from "../components/category/Drinks.jsx"
export {default as CategoryProducts} from "../components/category/CategoryProducts.jsx"